apiVersion: v1
kind: ReplicationController
metadata:
  name: todo-replication-controller
spec:
  replicas: 1
  selector:
    app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app
          image: sc10247/app-todo:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: "mongo-service"
            - name: MONGO_PORT
              value: "27017"
